<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        @page {
            margin: 20px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #000;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .header-table td {
            border: none;
            vertical-align: top;
        }

   .logo{
    width:90px;
    margin-top:12px;
}

     .company-name {
    font-size: 24px;
    font-weight: bold;
    text-align: center;
    margin: 0;
    color: #005BAC;
}
      .company-info {
    text-align: center;
    font-size: 11px;
    line-height: 18px;
    color: #444444;
}

       .divider {
    border-top: 3px solid #005BAC;
    margin: 12px 0 18px;
}

       .report-title {
    text-align: center;
    font-size: 20px;
    font-weight: bold;
    margin-bottom: 18px;
    text-transform: uppercase;
    color: #005BAC;
}

        .report-info {
            width: 100%;
            margin-bottom: 15px;
        }

        .report-info td {
            border: none;
            padding: 3px 0;
            font-size: 11px;
        }

        .summary {
            width: 100%;
            margin-bottom: 18px;
        }

.summary td{
    background:#EEF6FF;
    border:1px solid #005BAC;
    padding:12px;
}

        .summary-title {
            font-size: 10px;
            font-weight: bold;
        }

    .summary-value {
    font-size: 16px;
    font-weight: bold;
    margin-top: 6px;
    color: #005BAC;
}

        .data-table {
            width: 100%;
            border-collapse: collapse;
        }

        .data-table th,
        .data-table td {
            border: 1px solid #000;
            padding: 6px;
            font-size: 11px;
        }

 .data-table th {
    background: #005BAC;
    color: #FFFFFF;
    text-align: center;
}

tfoot th{
    background:#DCEEFF;
    color:#005BAC;
    font-weight:bold;
}

        .right {
            text-align: right;
        }

        .center {
            text-align: center;
        }

       .footer {
    margin-top: 20px;
    border-top: 2px solid #005BAC;
    padding-top: 10px;
    text-align: center;
    font-size: 10px;
    color: #555;
}

.page-number {
    position: fixed;
    bottom: -5px;
    right: 0;
    font-size: 10px;
    color: #666;
}
    </style>

</head>

<body>

    <table class="header-table">

        <tr>

            <td width="15%">

<img src="{{ public_path('images/fourstep_logo.png') }}" style="width:90px;">

            </td>

            <td>

                <div class="company-name">

                    FOURSTEP RETAIL LIMITED

                </div>

                <div class="company-info">

            Nimeta to parsipura road, 
            At.Nimeta, Ta.Waghodiya, 
            Dist.vadodara. 390019

                    <br>

                    Email :
                    support@fourstepretail.com

                    |

                    Phone :
                    +91 97262 86000

                </div>

            </td>

        </tr>

    </table>

    <div class="divider"></div>

    <div class="report-title">

        @yield('title')

    </div>

    <table class="report-info">

        <tr>

            <td width="35%">
         <span style="color:#005BAC;font-weight:bold;">Report Period :</span>
                {{ \Carbon\Carbon::parse($from)->format('d M Y') }}
                -
                {{ \Carbon\Carbon::parse($to)->format('d M Y') }}
            </td>

            <td width="35%">
<span style="color:#005BAC;font-weight:bold;">Generated On :</span>
                {{ now()->format('d M Y h:i A') }}
            </td>

            <td width="30%" class="right">
            <span style="color:#005BAC;font-weight:bold;">Generated By :</span>
                Admin
            </td>

        </tr>

    </table>

    @yield('summary')

    @yield('content')

    <div class="footer">

        Generated from <strong>FourStep Admin Panel</strong>

    </div>
  <script type="text/php">
if (isset($pdf)) {
    $font = $fontMetrics->get_font("Helvetica", "normal");
    $size = 10;

    $pdf->page_text(
        520,
        810,
        "Page {PAGE_NUM} of {PAGE_COUNT}",
        $font,
        $size,
        array(0,0,0)
    );
}
</script>

</body>

</html>