import React from "react";

function Terms() {
  return (
    <div className="bg-gray-50 min-h-screen py-6 sm:py-8 md:py-10 px-3 sm:px-4">

      <div className="max-w-6xl mx-auto bg-white border border-gray-200 rounded-2xl md:rounded-3xl shadow-sm overflow-hidden">

        {/* HEADER */}
        <div className="bg-gradient-to-r from-gray-50 to-white border-b px-4 sm:px-6 md:px-10 py-6 sm:py-8">
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-gray-900">
            Terms & Conditions
          </h1>

          <p className="text-gray-600 mt-4 leading-7 text-sm sm:text-base">
            This document is an electronic record in terms of Information Technology Act, 2000 and
            rules there under as applicable and the amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
            system and does not require any physical or digital signatures.
          </p>
          <p className="text-gray-600 mt-4 leading-7 text-sm sm:text-base">
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations, Privacy Policy and Terms of Use for access or usage of our website: <b>www.fourstepretail.com</b>.
          </p>

          <p className="text-gray-600 mt-4 leading-7 text-sm sm:text-base">
            The domain name www.fourstepretail.com or (hereinafter referred to as "Website") is owned by M/s Fourstep Retail Private Limited, which is a registered company,
            having its head office at 15-A, Shrinathji Varnan, Pipalia, Vaghodia, Vadodara, Gujarat-391760, India (hereinafter referred to as “Fourstep”).
          </p>
        </div>

        {/* CONTENT */}
        <div className="p-4 sm:p-6 md:p-10 space-y-8 md:space-y-10">

          {/* IN GENERAL */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              In General
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Fourstep owns and operates the website with its full ownership & control. This document governs your relationship with Fourstep as a Customer / Direct Seller.
              Access to and use of this website and the products and services available through this website (collectively, the “Services”) are subject to the following terms, conditions, and notices (“Website Terms of Use”).
              By using the Services, you are agreeing to all of the website terms of use, as may be updated by us from time to time. You should check this page regularly to take notice of any changes we may have made to the website terms of use.
              <br /><br />

              Access to this website is permitted on a temporary basis, and we reserve the right to withdraw or amend the Services without notice. We will not be liable if for any reason this website is unavailable at any
              time or for any period. From time to time, we may restrict access to some parts or this entire website.
            </div>
          </section>

          {/* WEBSITE DISCLAIMER */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Website Disclaimer
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              The contents of this website are only for information purpose. Users are advised to rely on information posted herein for any purpose only after
              verification and confirmation of the same from authentic and authoritative sources. Neither Fourstep nor the website developer is responsible for
              any consequences that may arise out of using such information without verification / confirmation. There may be time gap in internet / online posting /
              transmission of information and availability of such information at browsers’ end. Exact status may be confirmed from source <b>www.fourstepretail.com</b>.
              We are running this website, to promote our business within our direct selling network. We are at 15-A, Shrinathji Varnan, Pipalia, Vaghodia, Vadodara, Gujarat-391760, India.
              The Payment Gateway, which we mentioned in this website, is our official account, the money collected from this website on behalf of Fourstep i.e. M/s Fourstep Retail Private Limited
              on the sale of products exclusively marketed by M/s Fourstep Retail Private Limited.
            </div>
          </section>

          {/* PROHIBITIONS */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Prohibitions
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              The services available on this website are for customers, who are interested and have requested to become a Customer / Direct Seller of the Fourstep. Once you register as a user,
              you will permit us to fill Fourstep registration form and to mention your name where ever your signature is required.
              <br /><br />
              You must not misuse this website:<b> www.fourstepretail.com </b> You will not: commit or encourage a criminal offense; transmit or distribute a virus, trojan, worm, logic bomb or any other material which is malicious,
              technologically harmful, in breach of confidence or in any way offensive or obscene; hack into any aspect of the service; corrupt data; cause annoyance to other users; infringe upon the rights of any other person’s proprietary rights;
              send any unsolicited advertising or promotional material, commonly referred to as “spam”; or attempt to affect the performance or functionality
              of any computer facilities of or accessed through this website. Breaching this provision would constitute a criminal offense and Fourstep will report any such breach to the relevant law enforcement authorities and disclose your identity to them. We will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data, or other proprietary material due to your use of this website or to your downloading of any material posted on it, or on any website linked to it.
            </div>
          </section>

          {/* INTELLECTUAL PROPERTY */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Intellectual Property, Software and Content
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              The intellectual property rights in all software and content (including photographic images) made available to you on or through this website remains the property of Fourstep or its licensors and are protected by copyright laws and treaties around the world.
              All such rights are reserved by Fourstep and its licensors. You may store, print, and display the content supplied solely for your own personal use. You are not permitted to publish, manipulate, distribute, or otherwise reproduce,
              in any format, any of the content or copies of the content supplied to you or which appears on this website nor may you use any such content in connection with any business or commercial enterprise.
            </div>
          </section>

          {/* TERMS OF SALE */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Terms of Sale
            </h2>
            <p className="mb-5 text-sm sm:text-base">
              By placing an order, you are offering to purchase a product on and subject to the following terms and conditions.
              All orders are subject to availability and confirmation of the order price. Dispatch times may vary according to availability and subject to any delays resulting from postal delays or force majeure for which we will not be responsible.
              <br /><br />
              In order to contract with Fourstep you must be over 18 years or 21 years (if in state of Maharashtra) of age. Fourstep retains the right to refuse any request made by you.
              If your order is accepted, we will inform you by email. When placing an order, you undertake that all details you provide to us are true and accurate,
              that you are an authorized user of the credit or debit card used to place your order and that there are sufficient funds to cover the cost of the goods. All prices advertised are subject to such changes.
            </p>
            <div className="space-y-5">

              <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
                <b>a) Our Contract</b>

                <br /><br />

                When you place an order, you will receive an acknowledgement e-mail confirming receipt of your order: this email will only be an acknowledgement and will not constitute acceptance of your order.
                A contract between us will not be formed until we send you confirmation by e-mail that the goods which you ordered have been dispatched to you. Only those goods listed in the confirmation e-mail sent at the time of dispatch will be included in the contract formed.
              </div>

              <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
                <b>b) Pricing and Availability</b>

                <br /><br />

                Whilst we try and ensure that all details, descriptions, and prices which appear on this website are accurate, errors may occur. If we discover an error in the price of any goods which you have ordered we will inform you of this as soon as possible and give you the option of reconfirming your
                order at the correct price or cancelling it. If we are unable to contact you, we will treat the order as cancelled. If you cancel and you have already paid for the goods, you will receive a full refund. Delivery costs will be charged in addition; such additional charges are clearly displayed where applicable and included in the ‘Total Cost.’
              </div>

              <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
                <b>c) Payment</b>

                <br /><br />

                There are various methods of payment used by Fourstep. These methods of payment can be online either through wallets / debit / credit card or account transfer. Upon receiving your order, we carry out a standard authorization check on your payment card to ensure
                there are sufficient funds to fulfill the transaction. Your card will be debited upon authorization being received. The amount received upon the debiting of your card shall be treated as a deposit against the value of the goods you wish to purchase. Once the goods
                have been dispatched and you have been sent a confirmation email the amount paid as a deposit shall be used as consideration for the value of goods you have purchased as listed in the confirmation email.
              </div>

              <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
                <b>d) Customer / Direct Seller</b>

                <br /><br />

                Upon receiving your request to become Customer / Direct Seller with the Company, that he / she has read, understood, and accepted all
                the terms and conditions on the Application + Contract Form and Fourstep through its separate Marketing Plan to provide incentives to
                its exclusive Direct Sellers and agrees to comply by all the terms laid down. To become a Direct Seller of Fourstep is free. This document is uploaded on the website: <b>www.fourstepretail.com</b>.
                Direct Seller of the company also agrees to read and comply by further amendments, which will be made from time to time from Fourstep.
              </div>

            </div>
          </section>

          {/* DISCLAIMER OF LIABILITY */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Disclaimer of Liability
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              The content presented on the website <b>www.fourstepretail.com</b> is provided without any guarantees, conditions, or warranties regarding its accuracy. Unless explicitly
              stated otherwise and to the fullest extent allowed by law, Fourstep, along with its suppliers, content providers, and advertisers, disclaims all implied conditions, warranties,
              and other terms that may be implied by statute, common law, or equity. Furthermore, Fourstep shall not be held liable for any form of damages, including but not limited to
              direct, indirect, special, consequential, punitive, or incidental damages, as well as damages for loss of use, profits, data, or other intangible assets, harm to goodwill or reputation,
              or expenses incurred in acquiring substitute goods and services. These damages may arise from or be connected to the use, inability to use, performance, or failures of this website and any materials posted on it,
              regardless of whether such damages were foreseeable or arise in contract, tort, equity, restitution, by statute, at common law, or by any other means.
              This disclaimer does not affect Fourstep's liability for death or personal injury resulting from negligence, fraudulent misrepresentation, or misrepresentation of a fundamental matter, or any other liability that cannot be excluded or limited under applicable law.

            </div>
          </section>

          {/* LINKING */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Linking to this Website
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Our website may include links to other websites that may be of interest to you. However, once you use these links to exit our website,
              please be aware that we do not have any control over these other websites. Consequently, we cannot take responsibility for the protection and privacy of
              any information you provide while visiting such websites. These external websites are not governed by this privacy statement.
              We recommend exercising caution and reviewing the privacy statement applicable to the specific website you are visiting.
            </div>
          </section>

          {/* INDEMNITY */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Indemnity
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Customers and Direct Sellers agree to indemnify, defend, and hold harmless Fourstep, along with its directors, officers, employees, consultants, agents, and affiliates, from any and all third-party claims, liability, damages,
              and associated costs (including, but not limited to, legal fees). These claims and costs may arise due to your use of this website or your violation of the website terms of use.
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Modification of Website Terms of Use
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Fourstep reserves the right, at its absolute discretion and without prior notice, to modify, remove,
              or change the Services and / or any page of this website, as well as its policies.
            </div>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Invalidity
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              If any portion of these website terms of use is deemed unenforceable,
              including any provision where we limit our liability to you, the enforceability
              of the remaining parts of the website terms of use will not be affected, and all
              other clauses will remain in full force and effect. If possible, any clause, sub-clause,
              or part of a clause / sub-clause that can be separated to make the remaining portion valid will be interpreted accordingly.
              Alternatively, you agree that the clause will be adjusted and interpreted in a manner that closely
              aligns with the original meaning of the clause / sub-clause to the extent permitted by law.
            </div>
          </section>


          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Complaints
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              We operate a complaint handling procedure which we will use to try to resolve disputes when
              they first arise, please let us know if you have any complaints or comments.
            </div>
          </section>


          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Waiver
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              If you breach these conditions and we take no action, we will still be entitled to use our
              rights and remedies in any other situation where you breach these conditions.
            </div>
          </section>

          {/* CONTACT */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Communication with Customers / Direct Sellers
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Fourstep is committed to keeping our customers / Direct Sellers informed about our Product / Service Promotions through SMS and emails. Additionally,
              we send regular Transactional SMS and emails to our Customers / Direct Sellers from the email address:
              <b>support@fourstepretail.com</b>. If you have any inquiries or questions regarding the website's terms
              of use, please do not hesitate to contact us by emailing us at the following email address: <b>
                support@fourstepretail.com. </b>


            </div>
          </section>

          {/* TERMINATION */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Termination
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              Fourstep reserves the right to take appropriate action in the event that any member of the website is found to have engaged in counterfeiting or violated the website terms of use.
              This includes the company's authority to terminate the user account and pursue penalties through legal proceedings as deemed necessary.
            </div>
          </section>

          {/* GOVERNING LAW */}
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold mb-5 text-gray-900">
              Governing Law
            </h2>

            <div className="border border-gray-200 rounded-xl md:rounded-2xl p-4 sm:p-6 bg-gray-50 text-gray-700 leading-7 sm:leading-8 text-sm sm:text-base">
              The website terms of use are crafted in a clear and understandable manner and are governed by
              the laws of India. Accordingly, any disputes or conflicts, whether directly or indirectly related to these website terms of use and associated with this website, must be exclusively brought before the appropriate courts in Vadodara (Gujarat, India). These courts are vested with the relevant jurisdiction. If your disputes are found to
              be in violation of these terms, you will be held responsible for any penalties imposed by the jurisdiction.
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}

export default Terms;